SRCS := ./pll.v \
        ./soc_fpga_top.v \
        ../../soc.v \
        ../../tx_uart.v \
        ../../rx_uart.v \
        ../../fifo.v \
        ../../spi.v \
        ../../spi_nor_flash.v \
        ../../gpio.v \
        ../../cache.v \
        ../../cache_sram_I$$.v \
        ../../cache_sram_D$$.v \
        ../../dcache.v \
        ../../icache.v \
        ../../sram_sp.v \
        ../../sdram/mt48lc16m16a2_ctrl.v \
        ../../kianv-rv32-linuxcore/alu.v \
        ../../kianv-rv32-linuxcore/alu_decoder.v \
        ../../kianv-rv32-linuxcore/associative_cache.v \
        ../../kianv-rv32-linuxcore/clint.v \
        ../../kianv-rv32-linuxcore/control_unit.v  \
        ../../kianv-rv32-linuxcore/csr_decoder.v \
        ../../kianv-rv32-linuxcore/csr_exception_handler.v \
        ../../kianv-rv32-linuxcore/csr_unit.v \
        ../../kianv-rv32-linuxcore/datapath_unit.v \
        ../../kianv-rv32-linuxcore/design_elements.v \
        ../../kianv-rv32-linuxcore/design_elements_fpgacpu_ca.v \
        ../../kianv-rv32-linuxcore/divider.v \
        ../../kianv-rv32-linuxcore/divider_decoder.v \
        ../../kianv-rv32-linuxcore/extend.v \
        ../../kianv-rv32-linuxcore/interrupt_controller.v \
        ../../kianv-rv32-linuxcore/kianv_sv32.v \
        ../../kianv-rv32-linuxcore/load_alignment.v \
        ../../kianv-rv32-linuxcore/load_decoder.v \
        ../../kianv-rv32-linuxcore/main_fsm.v \
        ../../kianv-rv32-linuxcore/multiplier.v \
        ../../kianv-rv32-linuxcore/multiplier_decoder.v \
        ../../kianv-rv32-linuxcore/multiplier_extension_decoder.v \
        ../../kianv-rv32-linuxcore/plic.v \
        ../../kianv-rv32-linuxcore/register_file.v \
        ../../kianv-rv32-linuxcore/store_alignment.v \
        ../../kianv-rv32-linuxcore/store_decoder.v \
        ../../kianv-rv32-linuxcore/sv32.v \
        ../../kianv-rv32-linuxcore/sv32_table_walk.v \
        ../../kianv-rv32-linuxcore/sv32_translate_data_to_physical.v \
        ../../kianv-rv32-linuxcore/sv32_translate_instruction_to_physical.v \
